### ISSUE TITLE
Content search proposal

### ISSUE THREAD

**Issue by geksilla** [eliaslebid/angular-bookshelf#1]
Nice project!
I have a proposal regarding content search implementation.
I see that you have 3 types of sources Book, Author and Genre. You can add search using [ng-select](https://ng-select.github.io/ng-select#/filter).

It will help you to handle autocomplete and content grouping in a quite simple way. For demo purpose you can make 3 requests each for single entity to fetch appropriate resources, merge results into one stream, map it to format that conforms with ng-select data structure to display groups and navigate to appropriate book/author/genre page by selected item. 

P.S. Feel free to close this issue if you don't want to implement this.

**Comment by eliaslebed** [comment]
Thanks, @geksilla!

Much appreciated for the neat advice. I will be elaborating on this issue today and close it as soon as possible.

**Comment by eliaslebed** [comment]
Closing issue with [e73b0f9](https://github.com/eliaslebid/angular-bookshelf/commit/e73b0f9197ecaae471bfc0cd1badf07500b8c955) commit, feel free to open a new one if needed.
